# Generated by Django 5.0.4 on 2024-04-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_schll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schll',
            new_name='rstr',
        ),
    ]
